# set.ignore.stderrOption
# get.ignore.stderrOption
# set.stop_on_no_flags_parasOption 
# get.stop_on_no_flags_parasOption
# set.echoCmdOption
# get.echoCmdOption
# set.useInternOption
# get.useInternOption
# set.legacyExecOption
# get.legacyExecOption
# set.defaultFlagsOption
# get.defaultFlagsOption
# set.suppressEchoCmdInFuncOption
# get.suppressEchoCmdInFuncOption
